import 'package:flutter/material.dart';

import '../../../core/decision_engine/decision_result.dart';

class RiskAnalysisCard extends StatelessWidget {
  final DecisionResult result;

  const RiskAnalysisCard({
    super.key,
    required this.result,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(24),
      ),
      child: Padding(
        padding: const EdgeInsets.all(22),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [

            const Row(
              children: [

                Icon(
                  Icons.shield_rounded,
                  color: Color(0xFF2563EB),
                ),

                SizedBox(width: 10),

                Text(
                  "Risk Analysis",
                  style: TextStyle(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                  ),
                ),

              ],
            ),

            const SizedBox(height: 20),

            Row(
              children: [

                const Expanded(
                  child: Text(
                    "Risk Score",
                    style: TextStyle(fontSize: 16),
                  ),
                ),

                Text(
                  "${result.riskScore} / 20",
                  style: const TextStyle(
                    color: Colors.green,
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),

              ],
            ),

            const SizedBox(height: 16),

            ClipRRect(
              borderRadius: BorderRadius.circular(20),
              child: LinearProgressIndicator(
                value: result.riskScore / 20,
                minHeight: 10,
                backgroundColor: Colors.grey.shade300,
                color: Colors.green,
              ),
            ),

            const SizedBox(height: 24),

            Container(
              padding: const EdgeInsets.all(18),
              decoration: BoxDecoration(
                color: const Color(0xFFEFFAF3),
                borderRadius: BorderRadius.circular(18),
              ),
              child: const Row(
                children: [

                  Icon(
                    Icons.verified,
                    color: Colors.green,
                  ),

                  SizedBox(width: 12),

                  Expanded(
                    child: Text(
                      "Risk score is now generated by the Quanttora Decision Engine.",
                      style: TextStyle(
                        height: 1.5,
                      ),
                    ),
                  ),

                ],
              ),
            ),

          ],
        ),
      ),
    );
  }
}